'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { AppContext } from "@/context/AppContext";
import { useState } from 'react'
import { UserStatus } from '@/enums/enums'
import PointerGlow from './components/BackgroundEffects/PointerGlow'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [userStatus, setUserStatusTo] = useState<UserStatus>(
    UserStatus.LoggedOut
  );
  return (
    <html lang="en">
      <body > <AppContext.Provider value={{ userStatus, setUserStatusTo }}>
        <PointerGlow userStatus={userStatus} />
        {children}
      </AppContext.Provider></body>
    </html>
  )
}
